spring:
  application:
    name: book-managment
  datasource:
    url: jdbc:mysql://localhost:3306/books_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/book-realm
      client:
        registration:
          keycloak:
            client-id: book-client
            client-secret: 94gV150Xnt9ZRrxM3xyx5BqxcN9BnMxj
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/book-realm

server:
  port: 8087